---
- hosts: devops
  become: true
  tasks:
   - name : insstalling httpd
     yum:
      name: httpd
      state: latest
      
   - name: Copy index.html
     copy:
      src: /root/index.html
      dest: /var/www/html/index.html

   - name: Start the apache server
     service:
      name: httpd
      state: started
...
