---
- hosts: devops
  become: true
  tasks:
   - name: Ensure yum-utils is installed
     yum:
      update_cache: yes
      state: present
      name: "yum-utils"

   - name: Run "yum upate"
     yum:
      update_cache: yes
      name: "*"
      state: latest

   - name: restart system to reboot to newest kernel
     shell: "sleep 5 && reboot"
     async: 1
     poll: 0

