---
- hosts: devops
  become: true
  tasks:
   - name: Build a schedule play book for silvextech environment
     tower_schedule:
       name: "{{ sched1 }}"
       state: present
       unified_job_template: "Demo Job Template"
       rrule: "DTSTART:20220727T130551Z RRULE:FREQ=WEEKLY;INTERVAL=1;COUNT=1"
     register: result
     
